version: "3.9"
services:
  postgres:
    container_name: football_db
    image: postgres:15
    restart: always
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes:
      - ./src/database/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
